version: '3'

services:
  reactapp:
    container_name: reactjs
    restart: unless-stopped
    build: ./client
    command: sh -c "/wait && cd reactapp && npm start"
    volumes:
      - ./client:/reactapp
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - nodejs
    environment:
      WAIT_HOSTS: nodeserver:7000

  nodejs:
    container_name: nodeserver
    restart: unless-stopped
    build: ./server
    command: sh -c "/wait && cd app && nodemon"
    volumes:
      - ./server:/app
    ports:
      - "7000:7000"
    networks:
      - app-network
    links:
      - db
    environment:
      WAIT_HOSTS: mongodb:27017
      
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    env_file: server/.env
    ports:
      - "27017:27017"
    volumes:     
      - ./data:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge